import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import React from "react";
import Nav from "react-bootstrap/Nav";
import styles from './Layout.module.scss';

const name = '[Your Name]'
export const siteTitle = 'Next.js Sample Website'

export default function Layout({
    children,
    home
}: {children: React.ReactNode,
home?: boolean}) {
    return (
      <>
      <Head>
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Generated by create next app" />
        <meta name="og:title" content={siteTitle} />
      </Head>

      <header className={styles.header}>
      <Nav
        activeKey="/home"
        onSelect={(selectedKey) => console.log(selectedKey)}
      >
        <Nav.Item>
          <Link href="/" passHref>
            <Nav.Link className={styles.navLink}>Home</Nav.Link>
          </Link>
        </Nav.Item>
        <Nav.Item>
          <Link href="/dashboard" passHref>
            <Nav.Link className={styles.navLink}>Dashboard</Nav.Link>
          </Link>
        </Nav.Item>
        <Nav.Item>
          <Link href="/employee/list" passHref>
            <Nav.Link className={styles.navLink}>Employee Manager</Nav.Link>
          </Link>
        </Nav.Item>
      </Nav>
       
      </header>
      <div className={styles.container}>

<main className={styles.main}>{children}</main>

<footer className={styles.footer}>
  <a
    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    target="_blank"
    rel="noopener noreferrer"
  >
    Powered by{' '}
    <span className={styles.logo}>
      <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} layout='fixed' />
    </span>
  </a>
</footer>
</div>
      </>
    )
}